<?php

namespace WH\SeoBundle\Repository;

/**
 * MetasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetasRepository extends \Doctrine\ORM\EntityRepository
{
}
