modal: 'true'

title: 'Editer une redirection'

formFields:
    - urlToRedirect
    - redirectionUrl
    - externalRedirectionUrl
    - redirectionType

footerFormFields:
    save:
        label: 'Enregistrer'
        field: 'save'
        color: 'success'